# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4UCqDNug3O8Z9aP68gvNJNB96aFbVl3
"""

import streamlit as st
import numpy as np
import joblib

# Load model
model = joblib.load("model.pkl")
scaler = joblib.load("scaler.pkl")

st.set_page_config(page_title="Dropout Prediction", layout="centered")

st.title("🎓 Student Dropout Prediction")
st.write("Sistem prediksi untuk mendeteksi risiko mahasiswa dropout")

# =========================
# INPUT USER
# =========================
st.subheader("📋 Input Data Mahasiswa")

age = st.number_input("Age at Enrollment", 17, 60, 20)
admission_grade = st.number_input("Admission Grade", 0.0, 200.0, 120.0)
prev_grade = st.number_input("Previous Qualification Grade", 0.0, 200.0, 110.0)

sem1_grade = st.number_input("1st Semester Grade", 0.0, 20.0, 12.0)
sem2_grade = st.number_input("2nd Semester Grade", 0.0, 20.0, 12.0)

sem1_approved = st.number_input("1st Sem Approved Units", 0, 20, 5)
sem2_approved = st.number_input("2nd Sem Approved Units", 0, 20, 5)

debtor = st.selectbox("Debtor", [0, 1])
scholarship = st.selectbox("Scholarship Holder", [0, 1])

# =========================
# PREPROCESSING
# =========================
input_data = np.array([[
    age,
    admission_grade,
    prev_grade,
    sem1_grade,
    sem2_grade,
    sem1_approved,
    sem2_approved,
    debtor,
    scholarship
]])

input_scaled = scaler.transform(input_data)

# =========================
# PREDICTION
# =========================
if st.button("🔍 Predict"):
    prediction = model.predict(input_scaled)[0]
    prob = model.predict_proba(input_scaled)[0][1]

    st.subheader("📊 Hasil Prediksi")

    if prediction == 1:
        st.error(f"⚠️ Mahasiswa berisiko Dropout ({prob:.2%})")
    else:
        st.success(f"✅ Mahasiswa tidak berisiko Dropout ({prob:.2%})")

    # Insight sederhana
    st.markdown("### 💡 Insight")
    if sem1_grade < 10 or sem2_grade < 10:
        st.write("- Performa akademik rendah menjadi faktor utama risiko dropout")
    if debtor == 1:
        st.write("- Status finansial (debtor) meningkatkan risiko")